#### Learning numpy (3)

In [ ]:

import numpy as np
a = np.arange(9) #3*3
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Reshape
b =a.reshape(3,3) #3*3=9
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### Convert 1D into 2D

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a.shape

(9,)

In [5]:
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [6]:
b.shape

(1, 9)

In [7]:
c = a[: ,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [9]:
# Array Slicing
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
# Can Multiple anything with Array
a*6
a+3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
a.sum()

np.int64(45)

In [13]:
a.mean()

np.float64(5.0)