#### learning Numpy (5)

##### Reshaping and flattening multidimensional arrays

In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x.flatten() # flatten will change the parent array to 1D array. It will not change the original array. It will return a new array.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr = x.flatten()
arr
arr[2] = 100
print(arr)
print(x) #it will not change the original array


[  1   2 100   4   5   6   7   8   9  10  11  12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##### How to save and load NumPy objects

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])

In [11]:
np.save('array_of_6.npy', a)

In [ ]:
# np.load() is used to load the array from the file. 
b = np.load('array_of_6.npy')
b

array([1, 2, 3, 4, 5, 6])

In [13]:
arr_2 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.savetxt('array_2.csv', arr_2)


In [15]:
np.loadtxt('array_2.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])