#### Learning Numpy (2)

##### Array Functions

In [5]:
import numpy as np
a = np.array([10,12,14,16,18,2.3])
a

array([10. , 12. , 14. , 16. , 18. ,  2.3])

In [6]:
a.sort()  #there are so many Other Functions as well
a

array([ 2.3, 10. , 12. , 14. , 16. , 18. ])

In [8]:
b = np.array([10.2,5.3,12,16,17])
b

array([10.2,  5.3, 12. , 16. , 17. ])

In [9]:
np.concatenate((a,b))

array([ 2.3, 10. , 12. , 14. , 16. , 18. , 10.2,  5.3, 12. , 16. , 17. ])

In [11]:
c = np.concatenate((a,b))
c.sort()
c

array([ 2.3,  5.3, 10. , 10.2, 12. , 12. , 14. , 16. , 16. , 17. , 18. ])

##### 2-D Arrays

In [12]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
y = np.array([[11,22,33,44,55],[66,77,88,99,100]])
y
#y.ndim

2

In [17]:
z = np.concatenate((x,y), axis=0)
z

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  22,  33,  44,  55],
       [ 66,  77,  88,  99, 100]])

In [19]:
z = np.concatenate((x,y), axis=1)
z

array([[  1,   2,   3,   4,   5,  11,  22,  33,  44,  55],
       [  6,   7,   8,   9,  10,  66,  77,  88,  99, 100]])

In [21]:
n = np.array([
    [[ 1,   2,   3,   4,   5], 
     [6,   7,   8,   9,  10]],

     [[ 2,   5,   6,   3,   9], 
     [2,   8,   3,   9,  1]],

     [[ 6,   7,   8,   9,  10], 
     [2,   5,   6,   3,   9]],

    ])
n

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 2,  5,  6,  3,  9],
        [ 2,  8,  3,  9,  1]],

       [[ 6,  7,  8,  9, 10],
        [ 2,  5,  6,  3,  9]]])

In [ ]:
# to find The Number of Dimension
n.ndim
type(z) #it is not showing the dimension of array

numpy.ndarray

In [ ]:
z.size  #number of elements

20

In [29]:
n.shape

(3, 2, 5)