### Learning Numpy 


In [1]:
# Importing The Library
import numpy as np

#### Creating an array using numpy

In [ ]:
food = np.array(['shawarma', 'Burger', 'sandwich']) #1D array
food


array(['shawarma', 'Burger', 'sandwich'], dtype='<U8')

In [5]:
price = np.array ([200,300,250])
price

array([200, 300, 250])

In [6]:
type(price)

numpy.ndarray

In [7]:
type(food)

numpy.ndarray

In [9]:
len(price)
len(food)

3

#### accessing any element an the array through index

In [11]:
price[:2]

array([200, 300])

In [12]:
food[2]

np.str_('sandwich')

In [ ]:
price.mean() #There are so many func (can apply through '.')
np.zeros(5) #array of zeros
np.ones(4) #array of Ones



array([1., 1., 1., 1.])

In [ ]:
np.arange(8)
np.arange(3,10)  #specific range

array([3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(3,20, 2)      #with specific intervel

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
# table of 5
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [25]:
# generating random numbers with specific intervel
np.linspace(1,20, num=5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [27]:
# Specifing datatype
np.ones(10, dtype=np.int64)
#Or
np.ones(10, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])