#### Learning Pandas (4)

##### Stack arrays 

In [1]:
import numpy as np 

In [2]:
arr1 = np.array([[1, 1, 1],[ 2,2,2]])
arr2 = np.array([[3, 3, 3],[ 4,4,4]])

In [ ]:
# For horizontal stacking
np.vstack((arr1, arr2))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [6]:
# For vertical stacking
np.hstack((arr1, arr2)) 

array([[1, 1, 1, 3, 3, 3],
       [2, 2, 2, 4, 4, 4]])

In [9]:
# Array Basic Operation 
data = np.array([1, 2, 3])
print (data.max())
print (data.min())
print (data.sum())

3
1
6


In [12]:
# genereate random integers between 0 and 4
print (np.random.randint(5, size=(2, 4)))

[[4 2 0 2]
 [1 1 0 3]]


#### Transpose of array

In [13]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [15]:
#OR 
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

##### Reversing an array

In [ ]:
# 1D array
arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,10])
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:

np.flip(arr)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [19]:
# 2D array 
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
np.flip(arr_2d)
np.flip(arr_2d, axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])